conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Imagen3 --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Recraft3 --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name LumaPhoton --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Flux1_1Pro --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Ideogram2 --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Dalle3 --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name StableDiffusion3_5 --category i
conda run -n seed --no-capture-output python eval_pipeline.py --model_name SeedLlama --category i
conda run -n anole --no-capture-output python eval_pipeline.py --model_name Anole --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Gemini2 --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name GPT4o --category i
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name BLIP3o --category i
conda run -n bagel --no-capture-output python eval_pipeline.py --model_name Bagel --category i
conda run -n janus --no-capture-output python eval_pipeline.py --model_name Janus --category i
conda run -n seed --no-capture-output python eval_pipeline.py --model_name SeedLlama --category it
conda run -n anole --no-capture-output python eval_pipeline.py --model_name Anole --category it
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name GPT4oAgent --category it
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name HybridAgent --category it
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name Gemini2 --category it
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name GPTImage --category it
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name StableAudio --category am
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name AudioLDM2 --category am
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name MusicGen --category am
conda run -n tango --no-capture-output python eval_pipeline.py --model_name TangoMusic --category am
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name YuE --category am
conda run -n spiritlm --no-capture-output python eval_pipeline.py --model_name SpiritLM --category at
conda run -n mmeval --no-capture-output python eval_pipeline.py --model_name VoxInstructAgent --category at
conda run -n voiceldm --no-capture-output python eval_pipeline.py --model_name VoiceLDMAgent --category at
